/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html", "./js/**/*.js"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        brand: "#6e86d6",
        primary: "#171818",
        "primary-container": "#2c2c2c",
        "on-primary": "#ffffff",
        "on-primary-container": "#949393",
        "inverse-primary": "#c8c6c5",
        secondary: "#3c6378",
        "secondary-container": "#bde5fe",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#40677d",
        tertiary: "#001a24",
        "tertiary-container": "#003040",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#7299ab",
        background: "#f9f9f9",
        "on-background": "#1a1c1c",
        surface: "#f9f9f9",
        "on-surface": "#1a1c1c",
        "surface-variant": "#e2e2e2",
        "on-surface-variant": "#444748",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f3",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        outline: "#747878",
        "outline-variant": "#c4c7c7",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
        "surface-tint": "#5f5e5e",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "container-padding-desktop": "40px",
        "container-padding-mobile": "20px",
        base: "8px",
        "bento-gap": "16px",
      },
      fontFamily: {
        headline: ["Spline Sans", "sans-serif"],
        display: ["Spline Sans", "sans-serif"],
        label: ["Spline Sans", "sans-serif"],
        body: ["Public Sans", "sans-serif"],
        serif: ["Cormorant Garamond", "serif"],
      },
      fontSize: {
        "display-lg": ["72px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
      },
      maxWidth: {
        site: "1440px",
      },
      transitionTimingFunction: {
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
